/*
 * Copyright 2018, OpenCensus Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.opencensus.contrib.http;

import static com.google.common.base.Preconditions.checkNotNull;

import io.opencensus.trace.Annotation;
import io.opencensus.trace.MessageEvent.Type;
import io.opencensus.trace.Span;
import io.opencensus.trace.SpanContext;
import io.opencensus.trace.Tracer;
import io.opencensus.trace.propagation.TextFormat;
import javax.annotation.Nullable;

/**
 * This helper class provides APIs for instrumenting HTTP servers.
 *
 * @since 0.13
 */
public class HttpServerHandler<Q, P> extends HttpHandler<Q, P> {

  /**
   * Creates a {@link HttpServerHandler} with given parameters.
   *
   * @param tracer the Open Census tracing component.
   * @param textFormat the {@code TextFormat} used in HTTP propagation.
   * @param extractor the {@code HttpExtractor} used to extract information from the
   *     request/response.
   * @since 0.13
   */
  public HttpServerHandler(Tracer tracer, TextFormat textFormat, HttpExtractor<Q, P> extractor) {
    super(tracer, textFormat, extractor);
  }

  @Override
  public String getSpanName(Q request, String method) {
    return String.format("Recv.%s", method);
  }

  /**
   * Instrument an incoming request before it is handled. By default it will de-serialize propagated
   * span context from the request and record the message size.
   *
   * <p>This method will create a span under the propagated parent context. If the parent context is
   * not present, the span will be created under the current context.
   *
   * <p>The name of the span would be generated by invoking {@link #getSpanName} with the parameter
   * {@code method}.
   *
   * <p>The generated span will NOT be set as current context. User can use the returned value to
   * control when to enter the scope of this span.
   *
   * @param <C> the type of the carrier
   * @param getter the getter used when extracting information from the {@code carrier}.
   * @param carrier the entity that holds the HTTP information.
   * @param request the request entity.
   * @param method the name of the receive method.
   * @return a span that represents the response handling process.
   * @since 0.13
   */
  public <C> Span handleRecv(TextFormat.Getter<C> getter, C carrier, Q request, String method) {
    checkNotNull(getter, "getter");
    checkNotNull(carrier, "carrier");
    checkNotNull(request, "request");
    Span span = null;
    try {
      SpanContext spanContext = textFormat.extract(carrier, getter);
      span =
          tracer.spanBuilderWithRemoteParent(getSpanName(request, method), spanContext).startSpan();
    } catch (Exception e) {
      // record this exception
      span = tracer.spanBuilder(getSpanName(request, method)).startSpan();
      span.addAnnotation(
          Annotation.fromDescription("Error parsing span context: " + e.getMessage()));
    }
    // record message size
    recordMessageEvent(
        span, nextRecvMessageEventId(), Type.RECEIVED, extractor.getRequestSize(request), 0L);
    return span;
  }

  /**
   * Instrument an outgoing response after it is sent. By default it will handle error, set the
   * status of current span and optionally end the span.
   *
   * @param response the received response.
   * @param error the error occurs when processing the response.
   * @param span the span that represents the request.
   * @param endSpan whether to close the span.
   * @since 0.13
   */
  public void handleSend(
      @Nullable P response, @Nullable Throwable error, Span span, boolean endSpan) {
    // record message size
    recordMessageEvent(
        span, nextSentMessageEventId(), Type.SENT, extractor.getResponseSize(response), 0L);

    // set status according to response
    span.setStatus(parseResponseStatus(response, error));

    // maybe end span
    if (endSpan) {
      span.end();
    }
  }
}
