workspace(name = "opencensus_examples")

git_repository(
    name = "grpc_java",
    remote = "https://github.com/grpc/grpc-java.git",
    tag = "v1.10.1",
)

load("//:opencensus_workspace.bzl", "opencensus_maven_jars")
load("@grpc_java//:repositories.bzl", "grpc_java_repositories")

opencensus_maven_jars()
grpc_java_repositories(
    # Omit to avoid conflicts.

    omit_com_google_auth_google_auth_library_credentials=True,
    omit_com_google_api_grpc_google_common_protos=True,
    omit_com_google_code_findbugs_jsr305=True,
    omit_com_google_code_gson=True,
    omit_com_google_errorprone_error_prone_annotations=True,
    omit_com_google_guava=True,
    omit_com_google_protobuf=True,
    omit_com_google_protobuf_nano_protobuf_javanano=True,
    omit_com_google_truth_truth=True,
    omit_com_squareup_okhttp=True,
    omit_com_squareup_okio=True,

    # These netty dependencies have already been included in opencensus_workspace.bzl
    omit_io_netty_buffer=True,
    omit_io_netty_common=True,
    omit_io_netty_handler_proxy=True,
    omit_io_netty_codec_http2=True,
    omit_io_netty_transport=True,
    omit_io_netty_codec=True,
    omit_io_netty_codec_socks=True,
    omit_io_netty_codec_http=True,
    omit_io_netty_handler=True,
    omit_io_netty_resolver=True,

    omit_io_opencensus_api=True,
    omit_io_opencensus_grpc_metrics=True,
    omit_junit_junit=True
)

# proto_library, cc_proto_library, and java_proto_library rules implicitly
# depend on @com_google_protobuf for protoc and proto runtimes.
# This statement defines the @com_google_protobuf repo.
http_archive(
    name = "com_google_protobuf",
    sha256 = "1f8b9b202e9a4e467ff0b0f25facb1642727cdf5e69092038f15b37c75b99e45",
    strip_prefix = "protobuf-3.5.1",
    urls = ["https://github.com/google/protobuf/archive/v3.5.1.zip"],
)
