name: Build Gradle Examples

on: 
  pull_request:
      branches:
      - master
      - v0.*

jobs:
  build:
    name: Build Gradle Examples Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: setup-java
        name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - uses: burrunan/gradle-cache-action@v1.10
        with:
          remote-build-cache-proxy-enabled: false
      - name: Build Examples
        working-directory: ./examples
        run: ./gradlew clean assemble --stacktrace && ./gradlew check && ./gradlew verGJF 
      - name: Build Spring Servlet example
        working-directory: ./examples/spring/servlet
        run: ./gradlew clean assemble --stacktrace && ./gradlew check && ./gradlew verGJF 