name: Build Maven Examples

on: 
  pull_request:
      branches:
      - master
      - v0.*

jobs:
  build:
    name: Build Maven Examples Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: setup-java
        name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - name: Build Examples
        working-directory: ./examples
        run: mvn --batch-mode --update-snapshots clean package appassembler:assemble -e
      - name: Build Spring Servlet example
        working-directory: ./examples/spring/servlet
        run: mvn --batch-mode --update-snapshots clean package appassembler:assemble -e